### ISSUE TITLE
Spotlight widgets not darken and cc looking buggy

### ISSUE THREAD

**Issue by imodder** [LaughingQuoll/NoctisXI#1]
ios 11.0.2
iPhone 7 Plus
Spotlight widgets not darkening and control center buggy.

Sshot:
https://pasteboard.co/Ha13BAo.png

https://pasteboard.co/Ha13QUn.png

**Comment by WillBishop** [comment]
Can also confirm. Control centre is unusable. Quite dissapointing, I've installed two paid tweak today from iOSCreatix, and had to uninstall both of them.

**Comment by WillBishop** [comment]
To be clear, my control centre has no background (no blur), and I can touch straight through it

**Comment by dallasgroot** [comment]
Same here, both with LittleX as well as stock.

**Comment by MiguelV95** [comment]
Having the same issues as WillBishop. Using an iPhone 7 Plus on iOS 11.1.2 Latest Electra build.

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.3
