### ISSUE TITLE
Barmoji is Inverted in App Store

### ISSUE THREAD

**Issue by maxprobably** [LaughingQuoll/NoctisXI#103]
The newest version seems to cause the emojis in Barmoji to invert. I’ve only noticed this in the App Store, though. Will update if I notice it anywhere else.

![054023de-4e6d-4b63-8d4b-a84e65cf78ce](https://user-images.githubusercontent.com/36049840/37082982-4722e202-21ab-11e8-8cf1-faeddb0865ed.png)

EDIT: Upon further inspection, all apps except messages seem to exhibit this issue.

**Comment by LaughingQuoll** [comment]
Fixed.
