### ISSUE TITLE
(iPad) Recent Apps's icons in Dock aren't visible, blank space only. Tapping those blank spaces by feel can still open the apps.

### ISSUE THREAD

**Issue by wellthisismartin** [LaughingQuoll/NoctisXI#11]
![28755167_1944136602517238_1352617097_o](https://user-images.githubusercontent.com/36987830/36895287-fb4d29b8-1e40-11e8-9144-d064b9b2a5d9.jpg)

**Comment by Maravishh51** [comment]
Yup. Having this same issue as well on an iPad Pro 10.5. 2 apps are invisible behind the empty space of the dock

**Comment by prodigydude** [comment]
Yeah I can confirm this on my iPad Pro 10.5. All 3 are blurred out.

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.5
