### ISSUE TITLE
Statusbar text still black in all enabled apps

### ISSUE THREAD

**Issue by Popm4n** [LaughingQuoll/NoctisXI#118]
![img_0071](https://user-images.githubusercontent.com/1069742/37096868-079badfc-21e8-11e8-8ce6-420d681ad388.PNG)

**Comment by Pwn20wnd** [comment]
You sure you're on the latest release and don't have any conflicts? It seems to be fine for me.

**Comment by Popm4n** [comment]
Yes

**Comment by LaughingQuoll** [comment]
What version?

**Comment by Popm4n** [comment]
1.0.6.2
