### ISSUE TITLE
Text is still black when 'Invert Tint Colour' is disabled.

### ISSUE THREAD

**Issue by Muirey03** [LaughingQuoll/NoctisXI#120]
When invert tint colour is disabled, the text in apps where dark mode is enabled is still black. I have an iPhone SE iOS 11.1.2 with NoctisXI v.1.0.6.2.

[Screenshots](https://imgur.com/gallery/nmVvZ)

**Comment by LaughingQuoll** [comment]
It's your theme.

**Comment by LaughingQuoll** [comment]
Disable the UI function of your theme
