### ISSUE TITLE
True Dark toggle still not working correctly

### ISSUE THREAD

**Issue by Muirey03** [LaughingQuoll/NoctisXI#122]
When the true Dark toggle is enabled, the background is the wrong colour. I have an iPhone SE iOS 11.1.2 with NoctisXI v.1.0.6.2.

[Screenshot](https://imgur.com/gallery/HtRlu)

**Comment by LaughingQuoll** [comment]
What tweak is making it blue?

**Comment by Muirey03** [comment]
@LaughingQuoll I'm pretty sure it is NoctisXI as I don't have any other tweaks that theme settings like that or anything and because it only happens when True Dark is enabled. Here is my tweak list though:

Anemone: 2.1.7-1
appinst (App Installer): 1.1
AppSync Unified: 9.0
Base Structure: 1-4
BigBoss Icon Set: 1.0
BioProtect X for iOS 11: 2.3-8
ByeByeHUD: 1.1.3
Cephei: 1.12
CertRemainTime: 2.3.4-2
Cydia Translations: 1.1.12
DarkMessages (iOS 10): 1.2.0-1
Darwin CC Tools: 877.5
DetailedBatteryUsage: 1.1.1
DetailedCellularUsage: 2.1.1
Ext3nder Installer: 16.5
Flame: 1.3
Flex 3 Beta: 1:3~Beta46
iCleaner Pro: 7.7.0~beta1
iOS Firmware: 11.1.2
iOS Toolchain: 6.1-1
iPhone Firmware (/sbin): 0-1
LD64: 253.3
libbulletin: 0.1-137
libcolorpicker: 1.6-1
libpackageinfo: 1.1.0.1-1
libswift4: 4.0.3-3
Link Identity Editor: 2:1.2.2-coolstar
LLVM+Clang: 3.7.1
Locale Profiles in UTF-8: 1.0-1
LockGlyph XI: 11.2
NewTerm 2: 2.0~beta3
NO PLS RECOVERY: 2.1.1
NoctisXI: 1.0.6.2
NotTodaySatan: 2.7.1
Pigeon: 0.0.1-5
pincrush: 0.9.2-2
PreferenceLoader: 2.2.4~alpha1
Profile Directory: 0-2
RespringModule: 1.0.0-1+debug
RocketBootstrap: 1.0.6~beta1
Safari Plus: 1.4.4
SCOthman For Snapchat: 12.7-8
Silo: 1.0.0-4+debug
SpectrePatch: 0.0.2
System Info: 1.2.1
TechSupport Framework: 1.5.0.1-1
TranslucentCydia: 0.9.0-1
TSS Saver: 1.2.0
Zeppelin: 2.1.0-12

**Comment by LaughingQuoll** [comment]
Is your settings usually that blue? Is the Anemone theme messing with it?

**Comment by LaughingQuoll** [comment]
Disable the UI function of your theme.

**Comment by Muirey03** [comment]
@LaughingQuoll Yes, it appears as though it is a conflict with my theme (Veexillum). It would be nice if you could resolve this conflict though as lots of people do use themes that theme UI elements. Veexillum doesn't actually theme the colours of the settings app, just the icons (such as Bluetooth, WiFi, etc.) and the toggle colour (from green when enabled to a navy colour) so it is still a glitch.

**Comment by LaughingQuoll** [comment]
> Veexillum doesn't actually theme the colours of the settings app

Wrong. It does, uninstall NoctisXI and take a look. It tints it.

**Comment by Muirey03** [comment]
Oh ok, my bad.
