### ISSUE TITLE
Lockscreen Completely blank after installation

### ISSUE THREAD

**Issue by Observer365** [LaughingQuoll/NoctisXI#15]
I8, 11.0.3

Electra 1.0.2

**Comment by sirius247** [comment]
I have this as well.

**Comment by josephm102** [comment]
i7, 11.0.3
E1.0.2
I have this as well,  uninstalled and reinstalled all my other tweaks to make sure there was no conflicts and the problem still remained.

**Comment by Punfetto** [comment]
I'm having the same issue with my i7+ 11.0.3.
Maybe there is a problem with the iOS version?
