### ISSUE TITLE
CC Toggle disaperad

### ISSUE THREAD

**Issue by nunobcm** [LaughingQuoll/NoctisXI#152]
I dont have CC toggle to turn noctix on/off

**Comment by LaughingQuoll** [comment]
Do you have silo installed? Is it set in your control center settings?

**Comment by nunobcm** [comment]
ok, i resinstaled silo and it apears now in control center. Thanks.

Atentamente, Nuno Ferreira




2018-03-12 9:54 GMT+00:00 LaughingQuoll <notifications@github.com>:
