### ISSUE TITLE
Message app (stock)

### ISSUE THREAD

**Issue by fuccboifarti** [LaughingQuoll/NoctisXI#155]
When you hold on a message to send reaction, the heart does not show up. You can click in the area where it is normally located and it’ll send. The icon itself is not showing up.

**Comment by Aransh** [comment]
I’m getting an icon where the heart is meant to be but it’s the “HaHa” icon (I basically have the “HaHa” icon twice)

**Comment by LaughingQuoll** [comment]
Screenshot

**Comment by fuccboifarti** [comment]
![Image](https://i.imgur.com/XuQc3N4.jpg)

**Comment by Aransh** [comment]
![Image](https://i.imgur.com/ThmZOyb.jpg)

**Comment by fuccboifarti** [comment]
It’s weird how my message received from another person has a slight great squat box around the bubble. I have no themes installed. ![Image](https://i.imgur.com/MwJyCdw.jpg)

**Comment by fuccboifarti** [comment]
I realized that when I apply system dark theme to the message app is when I get the grey box around the received messages.
