### ISSUE TITLE
Noctis XI breaks control centre

### ISSUE THREAD

**Issue by ElementalsTest** [LaughingQuoll/NoctisXI#16]
I'm using an iPhone SE on iOS 11.1.2 with Noctis v.1.0.2. Using NoctisXI removes most of my CC options:

[Screenshot](https://imgur.com/gallery/RvEHd)

**Comment by sirius247** [comment]
I have this same issue. Using iPhone 8, iOS 11.0

**Comment by sirius247** [comment]
If it helps... upon installing it gives a error about Silo, saying compatiblity issue or something.

**Comment by sumitkohli25** [comment]
I have the same problem it has removed cc options on please fix it as its not fixed on 1.0.2 NOCTISXI

**Comment by ElementalsTest** [comment]
Edit: It appears to be an issue with Silo not NoctisXI. You have to manually re-add the CC Controls from settings.

**Comment by sirius247** [comment]
You can't re-add sliders that are missing via the CC Controls from settings.

**Comment by ElementalsTest** [comment]
I could, they were called MediaControlsModule and AudioModule. You need to install Silo BEFORE installing NoctisXI because cydia installs in alphabetical order. Uninstall both of them then install Silo, respring, then install NoctisXI, respring. Then you will be able to add the controls back from settings.

**Comment by sirius247** [comment]
i'll try this
