### ISSUE TITLE
app which has dark mode opens with a white screen.. Can we load that sceen with Black color instead ?

### ISSUE THREAD

**Issue by aki91196** [LaughingQuoll/NoctisXI#164]
hey bro.. stock app that has dark mode applied through NoctisXI Loads with a white Screen.... it would be Great if it loads with the black Screen So many people are waiting for this feature.. thanks ;) https://www.reddit.com/r/jailbreak/comments/856t5e/request_love_to_see_if_app_with_darkmode_opens/?ref=share&ref_source=link
![noctis](https://user-images.githubusercontent.com/33560790/37560505-d540afc6-2a0f-11e8-8cb8-d803edbf4254.gif)

**Comment by LaughingQuoll** [comment]
wont fix
