### ISSUE TITLE
Can’t see settings options

### ISSUE THREAD

**Issue by nunobcm** [LaughingQuoll/NoctisXI#167]
Hi, after i switch system apps settings i can’t see settings options, it becames all black, how can i reset noctics settings?

**Comment by prodigydude** [comment]
I’m having this issue also, except the settings app if just all white.

**Comment by nunobcm** [comment]
See this link to solve the settings problem : http://www.jailbreakqa.com/questions/306020/how-to-reset-tweak-settings
