### ISSUE TITLE
Let us disable notifications

### ISSUE THREAD

**Issue by synthjunker** [LaughingQuoll/NoctisXI#168]
Have colorbanners 2 so i want it only on widgets and cc.

**Comment by LaughingQuoll** [comment]
This should now actually be possible. I'll take a look.

**Comment by sobersherlock** [comment]
Please let us disable notification center/cover sheet elements while you’re at it (in anticipation to ColorFlow for when it gets updated)

**Comment by LaughingQuoll** [comment]
@sobersherlock I'll add options to disable widgets, apps & notifications all separately.

**Comment by sobersherlock** [comment]
@LaughingQuoll music player too (just in case), if you can. Thanks in advance!
