### ISSUE TITLE
Issue with Notchless by SparkDev

### ISSUE THREAD

**Issue by tommoses** [LaughingQuoll/NoctisXI#17]
When launching settings with Notchless enabled and NoctisXI with apps enabled, noctis sets the colour of the status bar to show as dark when it should show as light colours since the background is black. This happens in the settings app for example. 
Example: https://youtu.be/LnupSv9kn3k

**Comment by tommoses** [comment]
Compatability* issue

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.3
