### ISSUE TITLE
I messup with NoctisXI 1.1 settings.

### ISSUE THREAD

**Issue by ios11iphone6s** [LaughingQuoll/NoctisXI#170]
When i turnoff : system wide goes white color
When i turn ON :  System wide goes black color

How to reset settings to default.

I can't see settings because it goes white/black. 

Which file is to delete to reset default settings.

I tried toggle on ControlCenter . i Clicked on it goes black color system wide. when i turn it off it goes white color system wide

**Comment by LaughingQuoll** [comment]
Delete all the NoctisXI plists in /var/mobile/Library/Preferences
