### ISSUE TITLE
Some text in music app not inverting.

### ISSUE THREAD

**Issue by maxprobably** [LaughingQuoll/NoctisXI#176]
Some text is not inverted in the stock music app, making it difficult to read
![img_0077](https://user-images.githubusercontent.com/36049840/38352541-c2ed98a6-3870-11e8-89ad-3bb43e350a21.PNG)
![img_0075](https://user-images.githubusercontent.com/36049840/38352542-c30b4dc4-3870-11e8-859c-64dc77474f2d.PNG)

**Comment by LaughingQuoll** [comment]
music isnt currently officially supported.
