### ISSUE TITLE
Nothing working

### ISSUE THREAD

**Issue by Defs3c** [LaughingQuoll/NoctisXI#180]
Hi, Im on iPhone 7 plus and I have enabled Noctis and nothing has gone to dark mode. I have tried respringing and nothing happens. Im on iOS 11.1.1. When I put apps in to compatibility mode, the colour changes though, am I supposed to do this for all apps or should they automatically go dark when noctis is enabled?

**Comment by LaughingQuoll** [comment]
You are supposed to enable which apps you want

It's not automatic.
