### ISSUE TITLE
PAlert text boxes incorrectly styled

### ISSUE THREAD

**Issue by ElementalsTest** [LaughingQuoll/NoctisXI#183]
The PAlert text box is incorrectly styled, even when the Noctis toggle is disabled.

[Screenshot](https://user-images.githubusercontent.com/36370942/39478194-9f0571f4-4d59-11e8-8263-9fb7f6c87a59.png)

**Comment by LaughingQuoll** [comment]
Contact the Palert dev with this issue. This seems like an issue on their end.
