### ISSUE TITLE
Sliders missing from CC upon install

### ISSUE THREAD

**Issue by sirius247** [LaughingQuoll/NoctisXI#23]
I had mentioned this in another issue but you guys closed it. The sliders are missing from the CC page. You can NOT add these back on from CC stock settings.

**Comment by ElementalsTest** [comment]
You need to install Silo BEFORE installing NoctisXI because cydia installs in alphabetical order. Uninstall both of them then install Silo, respring, then install NoctisXI, respring. Then you will be able to add the controls back from settings.

**Comment by sirius247** [comment]
I have already done this before posting this.
You dont understand you can NOT add sliders back from settings page. ONLY toggles.

I have done your advice several times before you suggest it. I initially installed Silo first.
