### ISSUE TITLE
CC not working properly

### ISSUE THREAD

**Issue by MiguelV95** [LaughingQuoll/NoctisXI#3]
When Noctis is turned on, the CC background disappears and you can touch thru it. Can’t swipe down to hide CC. Using an iPhone 7 Plus on iOS 11.1.2 with Electra 1.0.2

**Comment by Greensauce** [comment]
The ConnectivityModule buttons are misaligned when you add that back to the CC. 

https://i.imgur.com/gEGmITT.jpg

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.3
