### ISSUE TITLE
Editing contacts inside message app

### ISSUE THREAD

**Issue by PvDrags** [LaughingQuoll/NoctisXI#30]
Hitting the i then the contact name to edit the contact inside the message app brings up a transparent mess of information. Still usable but just completely see through.

**Comment by zpwn** [comment]
That happens with Dark Messages too.

**Comment by Oxycodon-IV** [comment]
I got this is exact Bug, and i dont have "Dark Messages" installed

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.4
