### ISSUE TITLE
Phone Keypad 

### ISSUE THREAD

**Issue by josephfduffy** [LaughingQuoll/NoctisXI#31]
Phone keypad is unusable. Input text (dialed numbers) is dark against dark background. And Keys are light, and look bad.

**Comment by ZPCigaars** [comment]
Yes after enabling true dark mode the number pad is not visible at all

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.6

**Comment by josephfduffy** [comment]
It’s now worse for me. Updated to 1.0.6. Screenshot attached. 11.1.2 on
iPhone X

**Comment by josephfduffy** [comment]
New version fixed it. Thanks!!
