### ISSUE TITLE
Wifi signal icon & locked symbol 

### ISSUE THREAD

**Issue by Oxycodon-IV** [LaughingQuoll/NoctisXI#34]
Settings —> Wi-Fi 

The icons on the right side beside each Wi-Fi name are too dark and not visible

Also, the wifi pop-up notification when you loose wifi signal, background is white

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.4

**Comment by Oxycodon-IV** [comment]
Great work, but No it has not been fixed m8
