### ISSUE TITLE
Silo breaks my Control center on iPad Pro 10.5

### ISSUE THREAD

**Issue by prodigydude** [LaughingQuoll/NoctisXI#40]
When install silo my control center breaks.
![912bbc37-7f10-43a2-adc9-efb909f72aa2](https://user-images.githubusercontent.com/36984253/36929340-14e298ce-1e44-11e8-9aa6-b8d1da9daf65.png)

**Comment by LaughingQuoll** [comment]
Re add the modules in the cc prefs.

**Comment by prodigydude** [comment]
You can’t re add the music control or the WiFi, Bluetooth etc controls.

**Comment by prodigydude** [comment]
There’s no option to re add music controls or WiFi, Bluetooth etc toggles.
