### ISSUE TITLE
No Dark mode in Safari and widgets are not reacting well

### ISSUE THREAD

**Issue by viperattack16** [LaughingQuoll/NoctisXI#41]
![91296c51-3128-4abb-ad52-e2b0a7910971](https://user-images.githubusercontent.com/37007685/36929796-fbc119a0-1ee9-11e8-9765-ca166f7c0b51.png)
![42330f06-f158-458d-bb21-f63671bbbae9](https://user-images.githubusercontent.com/37007685/36929797-fc1ba460-1ee9-11e8-8ee4-e49cd7d27887.png)

**Comment by LaughingQuoll** [comment]
I said limited app support.

Widgets issue noted.
