### ISSUE TITLE
Weather Widget Not Showing Temperature info with NoctisXI

### ISSUE THREAD

**Issue by imodder** [LaughingQuoll/NoctisXI#42]
Weather Widget Not Showing Temperature info with all vers of NoctisXI v1.0 - v1.0.2 - v1.0.3 - v1.0.4 - v1.0.5

ios 11.0.2
iphone plus

sshot:

https://pasteboard.co/Ha88WZe.jpg

**Comment by ZPCigaars** [comment]
It’s all showing properly just in the black text the text is not becoming white and that’s annoying

**Comment by LaughingQuoll** [comment]
Known issue.
