### ISSUE TITLE
LockScreen blurred out after installing NoctisXI

### ISSUE THREAD

**Issue by zyan910** [LaughingQuoll/NoctisXI#46]
![img_2785](https://user-images.githubusercontent.com/31066253/36932100-9004e5f4-1edd-11e8-9901-deccc7501768.PNG)

As shown in th picture above, the LS is blurred and only notifications show when swiping up
If i swipe to the widgets page, there is no blur, swiping back to the main page returns the blur

iPhone 6, iOS 11.0.1

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.5
