### ISSUE TITLE
CC Laggy and Modules are Squared, grey colored CC looks sorta bad

### ISSUE THREAD

**Issue by zyan910** [LaughingQuoll/NoctisXI#47]
The CC is grey and sometimes the toggles of the connectivity module are out of alignment (when not long pressed/3D Touched)

The CC opens up at like 15FPS

The CC opens modules up also at around 15FPS

iPhone 6, iOS 11.0.1

![img_2786](https://user-images.githubusercontent.com/31066253/36932132-3d8547aa-1ede-11e8-98b6-cff4183e3282.PNG)

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.5
