### ISSUE TITLE
Bug collection with examples

### ISSUE THREAD

**Issue by daniellwdb7** [LaughingQuoll/NoctisXI#48]
# Device: iPhone 6S iOS 11.1.2
### Noctis: 1.0.4

**Bug 1: Status bar text color does not change**
[Screenshot](https://imgur.com/a/PNgE6)

**Bug 2: CC starts scrolled down**
[Video](https://streamable.com/xdw4z)

**Bug 3: Fonts changes color from red to white**
[Video](https://streamable.com/sd1q8)

**Bug 4: Text color for search is not white**
[Screenshot](https://imgur.com/a/TocPS)

**Bug 5: White overlay on "more" text**
[Screenshot](https://imgur.com/a/APQxc)

**Bug 6: No white text on weather widget**
[Screenshot](https://imgur.com/a/mO25M)

**Bug 7: Toggling Noctis brings back the dock when it's disabled by Anemone**
When you choose to hide the dock using Anemone, it comes back when toggling Noctis using the Noctis switch in CC, you have to hit apply in Anemone again to hide the dock on springboard again.

**Comment by LaughingQuoll** [comment]
1. Fixed in 1.0.5

2. Silo Bug

3, 4, 5 will fix.

6. can't fix.
