### ISSUE TITLE
Nigh shift switch moves to right after respring just like airplane switch does in first release

### ISSUE THREAD

**Issue by leftkark** [LaughingQuoll/NoctisXI#49]
https://i.imgur.com/urg8obz_d.jpg?maxwidth=640&shape=thumb&fidelity=medium
iphone 7 11.1.2

**Comment by leftkark** [comment]
iphone 7 11.1.2

**Comment by LaughingQuoll** [comment]
For now just expand it then shrink it.

Will fix in a later update.
