### ISSUE TITLE
Noctisxi v1.0.2 caused to ugly rectangular block shapes again at cc - was fixed ar v 1.0 release

### ISSUE THREAD

**Issue by imodder** [LaughingQuoll/NoctisXI#5]
Hi, i updated v1.0.2 and again ugly rectangular block shapes occured at cc like beta stage!
It was fixed v1.0 release
Noctisxi V1.0 sshot
https://pasteboard.co/Ha13QUn.png

Noctisxi V1.0.2 sshot

https://pasteboard.co/Ha1gZBb.png

Device iphone plus
ios 11.0.2

Please solve this ugly rectangular block shapes

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.3
