### ISSUE TITLE
Silo 1.0.0-4 breaks control centre

### ISSUE THREAD

**Issue by ElementalsTest** [LaughingQuoll/NoctisXI#51]
When using Silo 1.0.0-4 on my iPhone SE, iOS 11.1.2, swiping up to access the CC only brings the CC up halfway and you have to swipe up again to access it fully.

[Screenshot](https://imgur.com/gallery/3IUkk)

**Comment by Revulate** [comment]
Please use the proper GitHub for reporting bugs. This is not a NoctisXI bug.
https://github.com/ioscreatix/Silo/issues

**Comment by imkpatil** [comment]
Goto the controlcenter settings & remove all the stock modules ( The one’s without an icon)
