### ISSUE TITLE
Description cells have white background with Noctis off

### ISSUE THREAD

**Issue by Aransh** [LaughingQuoll/NoctisXI#52]
In safe mode (as in, normally):
![Image](https://i.imgur.com/j8Dp7MA.jpg)
With Noctis off:
![Image](https://i.imgur.com/Ja4xYaR.jpg)

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.5

**Comment by Aransh** [comment]
Not fixed in 1.0.5.1... ![Image](https://i.imgur.com/MdNilkK.jpg)
