### ISSUE TITLE
Turning the Noctis toggle off makes the CC light even when light CC is disabled.

### ISSUE THREAD

**Issue by ElementalsTest** [LaughingQuoll/NoctisXI#53]
I have an iPhone SE on iOS 11.1.2 with NoctisXI v.1.0.4 and Silo v.1.0.0-4. I have disabled Light Control Centre in the NoctisXI settings but it's is treated as though it is still enabled. (Even after multiple resprings)

**Comment by Aransh** [comment]
Here too

**Comment by Revulate** [comment]
Same issue here. :/

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.5 (Packix)
