### ISSUE TITLE
3D Touch on messages app, no pictures

### ISSUE THREAD

**Issue by messerffm** [LaughingQuoll/NoctisXI#55]
Instead of pictures of my contacts there are white circles if I’m using 3D Touch on my messages app.
Same issue with the tweak „Manila“ if you are using 3D Touch on Folders, just white spaces instead of app icons

Isn’t fixed with 1.0.4 or 1.0.5 :(

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.5 (Packix)
