### ISSUE TITLE
No Translucency at all.

### ISSUE THREAD

**Issue by Muirey03** [LaughingQuoll/NoctisXI#56]
When using NoctisXI v.1.0.4 on my iPhone SE, iOS 11.1.2, there is no Translucency whatsoever on anything.

**Comment by LaughingQuoll** [comment]
Screenshots please.

**Comment by Muirey03** [comment]
@LaughingQuoll [Here you go](https://imgur.com/gallery/MZpAy) - On v.1.0.2 these headers were translucent but after updating to v.1.0.4 they are solid again. (Sorry I didn't make my issue very clear, things like notifications, folders, etc. are still translucent but there is no 'in-app' translucency)

**Comment by LaughingQuoll** [comment]
This isn't a bug.
