### ISSUE TITLE
Having Noctis with app darkmode and Eclipse X active at the same time causes some system apps to crash immediately open

### ISSUE THREAD

**Issue by MeltedBu11et** [LaughingQuoll/NoctisXI#57]
iPhone X 11.1.2, either disabling app darkmode in Noctis or turning off Eclipse X stops the crashing
Seems to only crash apps that Noctis darkmode takes effect in

**Comment by JamesBedwell** [comment]
From my understanding, NoctisXI is intended to be a full system-wide dark mode, therefore eclipse is not necessary.

**Comment by LaughingQuoll** [comment]
@JamesBedwell within reason. When app list is updated you can select which apps which tweaks will theme.
