### ISSUE TITLE
Snapchat not refreshing after installing Noctis

### ISSUE THREAD

**Issue by Awkivvo** [LaughingQuoll/NoctisXI#6]

**Comment by ElementalsTest** [comment]
Are you sure this is an issue with NoctisXI? Anemone causes this issue, try uninstalling NoctisXI and Silo and see if the issue still occurs. If it does, please close this issue as it's unrelated to NoctisXI.

**Comment by Awkivvo** [comment]
when i uninstalled noctis it worked, i reinstalled noctis, snapchat not refreshing again

**Comment by LaughingQuoll** [comment]
This isn't a noctis issue.
