### ISSUE TITLE
Known Issues with NoctisXI 1.0.5

### ISSUE THREAD

**Issue by LaughingQuoll** [LaughingQuoll/NoctisXI#62]
Fixed Issues:
1. Status Bar Color
2. Dialer pad being black.
3. App Store header bar not having white text.
4. Editing a contact has black text inputs.
5. White corners in photos.
6. Fixed delete banner in photos not being themed.
7. Music controls disappearing after toggle.
8. Music controls being white after respring when Noctis is off.
9. Addressed folder lag.
10. Contacts header being cut off.
11. Lack of transparency in bottom and top menu bars.
12. App Store search results not having white text.
13. App Store reviews section not being themed.
14. App Store product details not being themed.
15. App Store purchase buttons not being themed.
16. Contacts index not toggling.
17. Dial view not toggling background.
18. Notification action cell non cut edges.
19. UILabels not updating when they should.

Current intentionally disabled apps include:
1. Mail
2. Calendar
3. Music
4. Notes
5. Reminders

**Comment by jakeajames** [comment]
Can confirm dock's fixed

**Comment by dallasgroot** [comment]
![4b0e525b-80dd-4512-af11-07ff678ccc69](https://user-images.githubusercontent.com/7484579/36997257-e2440c96-206d-11e8-9fc5-9d4fda7a35de.png)
![30ff41b6-d414-4380-9405-1a34c03b7b2b](https://user-images.githubusercontent.com/7484579/36997258-e2620ebc-206d-11e8-88a8-3a7dadb4c54d.png)

It appears settings wifi bars and dial buttons aren’t visible

**Comment by dallasgroot** [comment]
Anyway to disable maps as well? CarPlay isn’t that fun to look at anymore haha 
![56db9b6c-e10c-438e-affc-b1c32185b26a](https://user-images.githubusercontent.com/7484579/37007887-6f50a3f8-2094-11e8-988a-bffe202f62b1.png)
![a8d0e342-83aa-4967-a12b-254575c604ab](https://user-images.githubusercontent.com/7484579/37007888-6f798f3e-2094-11e8-8d6c-35e9b8a8e0d3.png)
