### ISSUE TITLE
Settings app issue when selecting tabs on iPad Pro, also the toggle for show separators does not work.

### ISSUE THREAD

**Issue by prodigydude** [LaughingQuoll/NoctisXI#63]
When I select something in my settings the text disappears. The show separators toggle does not work, I have it turned of but continues to show the separators.
![21012472-c24e-4189-9f36-3f660cc50380](https://user-images.githubusercontent.com/36984253/36970315-00025194-201d-11e8-888f-440efb8f8b85.png)

**Comment by LaughingQuoll** [comment]
Duplicate.
