### ISSUE TITLE
App Store White Update & Open & More

### ISSUE THREAD

**Issue by mods2** [LaughingQuoll/NoctisXI#65]
![img_4764](https://user-images.githubusercontent.com/36996655/36970807-754b51c6-2072-11e8-8996-507de1fdf21f.PNG)

**Comment by ZPCigaars** [comment]
That white more is more annoying then update button

**Comment by mods2** [comment]
Indeed

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.6
