### ISSUE TITLE
Status bar is still not white on NotisXI 1.0.5.1

### ISSUE THREAD

**Issue by ZPCigaars** [LaughingQuoll/NoctisXI#66]

**Comment by prodigydude** [comment]
I don’t believe it’s supposed to make it white.

**Comment by ZPCigaars** [comment]
Status bar being white only in messages app and I even tried toggling off true dark mode off but still it’s black and it doesn’t look good

**Comment by NuggTV** [comment]
I have the same issue on my 6s. Statusbar is not readable in Applications tweaked by Noctis when  enabled for Applications is selected. Disabling True Dark Mode does not help either.

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.6
