### ISSUE TITLE
Numbers In Dialer

### ISSUE THREAD

**Issue by mods2** [LaughingQuoll/NoctisXI#68]
They are hard to see without the [True Dark] is toggled on in Noctis settings and completely gone when its enabled . iPhone 7 11.1.2
![img_4767](https://user-images.githubusercontent.com/36996655/36971715-60d7c712-2075-11e8-8e5b-ba89d7f36c94.PNG)
![img_4769](https://user-images.githubusercontent.com/36996655/36971725-653a0b26-2075-11e8-85c9-a7b048d9d875.PNG)

**Comment by ZPCigaars** [comment]
This has to be fixed ASAP

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.6
