### ISSUE TITLE
Emoji in contacts color inverted

### ISSUE THREAD

**Issue by giang288** [LaughingQuoll/NoctisXI#73]
Emoji in contacts and call history are displayed with inverted color

**Comment by LaughingQuoll** [comment]
Screenshot please.

**Comment by mods2** [comment]
Here you go
![photo_2018-03-06_03-08-59](https://user-images.githubusercontent.com/36996655/37008728-2f3f2da4-20ec-11e8-9a0d-f007b472d08b.jpg)
![photo_2018-03-06_03-08-59](https://user-images.githubusercontent.com/36996655/37008737-3d0cf0e2-20ec-11e8-9044-bfa4f4601e97.jpg)

**Comment by mods2** [comment]
Here you go
![photo_2018-03-06_03-08-59](https://user-images.githubusercontent.com/36996655/37008754-50c9f4f4-20ec-11e8-86cc-5a2ee369c859.jpg)
![photo_2018-03-06_03-08-57](https://user-images.githubusercontent.com/36996655/37008758-5528bfee-20ec-11e8-9d73-bc76a6794362.jpg)

**Comment by mods2** [comment]
Here is another one
![photo_2018-03-06_03-15-51](https://user-images.githubusercontent.com/36996655/37008889-f780133c-20ec-11e8-9e65-99a34f41b769.jpg)
![photo_2018-03-06_03-15-50](https://user-images.githubusercontent.com/36996655/37008893-fcc8e2ba-20ec-11e8-9c48-ec447e9a1ea2.jpg)

**Comment by mods2** [comment]
Also the emojis in the keyboard are inverted.
Basically all the emojis in the phone app are inverted.
![photo_2018-03-06_03-22-17](https://user-images.githubusercontent.com/36996655/37009049-c2961558-20ed-11e8-8a86-e6023c43cf62.jpg)

**Comment by giang288** [comment]
http://wl.is/y0vHZl.js

For the "miss call" sometimes emojis show correct color, sometimes being inverted.

**Comment by giang288** [comment]
Sorry wrong link https://imgur.com/a/sbHDR

**Comment by LaughingQuoll** [comment]
Added to known issues list.
