### ISSUE TITLE
Settings bug

### ISSUE THREAD

**Issue by thatkid427** [LaughingQuoll/NoctisXI#78]
The text in settings is all dark too. Can’t see anything. iPhone X running iOS 11.1 2

![b3d5952a-7f5e-4074-8b87-e26c41e32605](https://user-images.githubusercontent.com/37080284/36987553-9eff57b8-206a-11e8-8652-3cb0f9bdc363.png)

**Comment by LaughingQuoll** [comment]
Duplicate.
