### ISSUE TITLE
App Store and Mail

### ISSUE THREAD

**Issue by PingPong7717** [LaughingQuoll/NoctisXI#80]
The App store needs updated along with the mail app. There are patches of white and black and it's hard to read.

**Comment by mods2** [comment]
Are u sure u r on the latest noctis? Cuz he removed mail support

**Comment by PingPong7717** [comment]
Yea. I just checked it’s all good now

**Comment by mods2** [comment]
Ok the no need for the issue, close it.

**Comment by PingPong7717** [comment]
What about the App Store?

**Comment by mods2** [comment]
Its already adressed

**Comment by PingPong7717** [comment]
I’ll take it down when I get to school tomorrow. I don’t have time atm because I’m working. Sorry
