### ISSUE TITLE
True Dark toggle not working properly

### ISSUE THREAD

**Issue by ElementalsTest** [LaughingQuoll/NoctisXI#82]
When the true Dark toggle is enabled, settings isn't true Dark and when the true Dark toggle is disabled, settings is true Dark. Also, every app other than settings (that is still affected by Noctis) is always true Dark (when NoctisXI is enabled), whether the true Dark toggle is enabled or not.

[Screenshots](https://imgur.com/gallery/RYyvp)

**Comment by LaughingQuoll** [comment]
Added to the list.
