### ISSUE TITLE
White Notification Details When 3-D Touch [Only Twitter]

### ISSUE THREAD

**Issue by mods2** [LaughingQuoll/NoctisXI#85]
Its not fully dark. I tried Telegram, Whatsapp, Instagram, Twitch and Discord notifications and they are fine. Only Twitter notifications. 
![photo_2018-03-06_03-50-14](https://user-images.githubusercontent.com/36996655/37009877-89a1f92a-20f1-11e8-82ba-4c48d335ddb9.jpg)

**Comment by LaughingQuoll** [comment]
Can't fix.
