### ISSUE TITLE
Picker Views are horribly broken

### ISSUE THREAD

**Issue by Pwn20wnd** [LaughingQuoll/NoctisXI#96]
https://imgur.com/a/ejcr5

**Comment by LaughingQuoll** [comment]
Where is this?

**Comment by Pwn20wnd** [comment]
It's the preference panel of AppleBetas's Countdown tweak.

**Comment by LaughingQuoll** [comment]
Can you find an example in stock ios that this is present.

**Comment by Pwn20wnd** [comment]
When you open the health app for the first time it'll ask for your info. All the pickers there have the same thing. See --> https://imgur.com/a/4JlVX

**Comment by LaughingQuoll** [comment]
Fixed in 1.0.7
