### ISSUE TITLE
App Store Bugs

### ISSUE THREAD

**Issue by HenryB96** [LaughingQuoll/NoctisXI#97]
Can barely see the search text, and Barmoji keyboard is inverted (it is in a couple of other apps as well):
![img_0613](https://user-images.githubusercontent.com/8763569/37030878-7129f968-2134-11e8-8d81-6398a9fd8fc7.PNG)

Review text colour is hard to read:
![img_0612](https://user-images.githubusercontent.com/8763569/37030879-7289234c-2134-11e8-8726-f88f8ec16287.PNG)

White background underneath "More" label in updates:
![img_0611](https://user-images.githubusercontent.com/8763569/37030883-73a99694-2134-11e8-91d1-03c01cbb0a67.PNG)

**Comment by LaughingQuoll** [comment]
Duplicates
